# Configuration file for cloudlist enumeration agent

#- # provider is the name of the provider (Digitalocean)
#  provider: do
#  # profile is the name of the provider profile
#  profile: prod
#  # digitalocean_token is the API key for digitalocean cloud platform
#  digitalocean_token: xxxxx
#
#- # provider is the name of the provider (Scaleway)
#  provider: scw
#  # scaleway_access_key is the access key for scaleway API
#  scaleway_access_key: SCWXXXXXXXXXXXXXX
#  # scaleway_access_token is the access token for scaleway API
#  scaleway_access_token: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
#
#- # provider is the name of the provider (Amazon Web Services)
#  provider: aws
#  # profile is the name of the provider profile
#  profile: staging
#  # aws_access_key is the access key for AWS account
#  aws_access_key: AKIAXXXXXXXXXXXXXX
#  # aws_secret_key is the secret key for AWS account
#  aws_secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#
#- # provider is the name of the provider (Google Cloud Platform)
#  provider: gcp
#  # profile is the name of the provider profile
#  profile: logs
#  # gcp_service_account_key is the minified json of a google cloud service account with list permissions
#  gcp_service_account_key: '{xxxxxxxxxxxxx}'