discord:
  - id: "domains"
    discord_channel: "Bug bounty"
    discord_username: "test"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discordapp.com/api/webhooks/1137378317599768717/DJ67zTr5JhIOsNbNbrAOoJZniSompPlcfs62nZ89mrMFP_voBBETbT0ZuenZ_O2Inr6g"
